### ISSUE TITLE
Regarding img_reduce

### ISSUE THREAD

**Issue by luorix1** [hou-yz/MVDeTr#2]
Hello, I just wanted to ask about the significance of img_reduce being 12.

Assuming we use Wildtrack, the images will be 1920 * 1080.
The data loading part of the code will resize this to 1280 * 720 (2/3 of the original size) and is coded as multiplying by 8 and dividing by img_reduce (=12)

The only time the image is actually shrunk by a factor of 12 seems to be in the visualization code (I may be wrong).

In addition, for line 157 in mvdetr.py, I am having a bit of trouble understanding how this counteracts the effects of the augmentation we performed on the original imge.

Thank you and I look forward to hearing from you soon.

**Comment by luorix1** [comment]
Am I correct in thinking that the 12 comes from the ratio between the feature maps and the original images?
original images in Wildtrack are 1920 * 1080 while feature maps from ResNet18 (modified) are 160 * 90

**Comment by hou-yz** [comment]
Yes, it is correct that `img_reduce` corresponds to the ratio between original image size and the final output feature map size. There is a factor of 8 when first resizing the image input as there is an 8x downsampling inside the resnet.

**Comment by luorix1** [comment]
Ah, thank you for the validation. I did end up clearing this up in my head later on yesterday but now I can rest easy 😄 
Have a good one.
