### ISSUE TITLE
Train/Inference on other multi-view dataset

### ISSUE THREAD

**Issue by chengche6230** [hou-yz/MVDeTr#4]
Hi, thanks for the great work on multi-view detection model!

Can this model be trained/inferenced on other multi-view datasets such as EPFL or CAMPUS?
If so, what information and what spec. should I prepare for the training/inferencing?

Thanks for reply!

**Comment by hou-yz** [comment]
Hi!

Thank you for your interest. At this moment there is no official support for datasets other than MultiviewX and Wildtrack. Please feel free to implement your own. 

P.S., MVDet and MVDeTr both use the same hyper-parameters for MultiviewX and Wildtrack datasets. 

Best,
Yunzhong

**Comment by chengche6230** [comment]
Got it. Thanks for your speedy reply!

**Comment by sjchhhhh** [comment]
> Got it. Thanks for your speedy reply!

hi，Can you successfully move other data into this model? Are there any problems that need attention? I want to re-sample the Multiview data set to get a more dense data set, but I'm not sure what needs attention? Look forward to your reply, thank you!
