### ISSUE TITLE
Can you share the pretrained model again? The link is expired.

### ISSUE THREAD

**Issue by sithu31296** [hou-yz/MVDeTr#5]

**Comment by hou-yz** [comment]
Thank you for your interest.

I have updated the link access. please try it again. [link](https://anu365-my.sharepoint.com/:u:/g/personal/u6852178_anu_edu_au/EVNIQ4rklKJFl8kzKv_faBoBjss7KFacNEION9Cn9D8daQ?e=91bY6B)

**Comment by sithu31296** [comment]
Thank you.
