### ISSUE TITLE
The training results cannot be replicated.

### ISSUE THREAD

**Issue by HyCfl** [hou-yz/MVDeTr#7]
I trained several times using your original code. Even with the same parameter settings, the training results differ each time: there are variances between results with the same number of training epochs, and the final results from the training also exhibit differences, sometimes even significant ones. 
even when the --deterministic argument is set using parser.  add_argument('--deterministic', type=str2bool, default=True), differences still persist.
Is this normal? If not, how can I fix the problem

**Comment by hou-yz** [comment]
thank you for your interest. yes, this is normal and the code can indeed produce some variance in the results. 

in the paper, all results are averaged across 5 runs, which isn't exactly a 'fix' but can somewhat mitigate concerns about the variance.
